import Head from "next/head";
import CountryList from "../components/CountryList";
import Header from "../components/Header";
import useFetch from "../hooks/useFetch";
import { useState } from "react";
import { useTheme } from "next-themes";

export default function Home() {
  const { theme, setTheme } = useTheme();
  const {
    data: countries,
    isPending,
    error,
  } = useFetch("https://restcountries.com/v3.1/all");
  let [countriesCount, setCountriesCount] = useState(12);
  const [activeBtn, setActiveBtn] = useState(true);

  const handleLoadMore = () => {
    setActiveBtn(false);
    setTimeout(() => {
      setActiveBtn(true);
      setCountriesCount((countriesCount += 8));
    }, 120);
  };

  return (
    <div className="prose md:prose-xl dark:prose-dark dark:md:prose-xl-dark">
      <Head>
        <title>REST Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setTheme={setTheme} theme={theme} />
      {error && <div>{error}</div>}
      {countries && (
        <CountryList countries={countries} countriesCount={countriesCount} />
      )}
      <div className="flex justify-center items-center mt-5">
      {isPending ? (
        <div>Loading...</div>
      ) : (
        <button
          type="button"
          className="p-3 rounded-lg border-1 text-sm font-semibold bg-slate-400 my-5"
          onClick={handleLoadMore}
        >
          Load More
        </button>
      )}
      </div>
    </div>
  );
}
